export type Products = {
  id: string; // uuid
  store_id: string;

  name: string;
  thumbnail_image: string;
  content: string;
  model?: string|null;
  discount_rate: number;
  image: string;

  inventory: number;
  price: number;

  options: Record<string, unknown>; // json

  state: string;

  created_at: string;
  updated_at?: string;

  category: string;
};

export const mockProducts = [
  {
    id: '1',
    store_id: 'store_1',
    name: '프리미엄 볼펜 민트 001',
    thumbnail_image: '/images/products/write/001.jpg',
    content: '감성문구의 프리미엄 감성을 담은 볼펜 상품입니다.',
    model: null,
    discount_rate: 0,
    image: '/images/products/write/001.jpg',
    inventory: 28,
    price: 5200,
    options: {
      color: ['black', 'blue'],
      size: ['0.5', '0.7'],
    },
    state: 'ACTIVE',
    created_at: '2025-09-01',
    updated_at: '2025-09-01',
    category: 'writing',
  },
  {
    id: '2',
    name: '라이트 만년필 그레이 002',
    category: 'writing',
    price: 64600,
    discount_rate: 0,
    inventory: 42,
    image: '/images/products/write/002.jpg',
    description: '감성문구의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
    options:{
      color:['black','blue'],
      size:[200,400]
    },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '3',
    name: '소프트 볼펜 브라운 003',
    category: 'writing',
    price: 2900,
    discount_rate: 25,
    inventory: 31,
    image: '/images/products/write/003.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
    options:{
      color:['black','blue'],
      size:[200,400]
    },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '4',
    name: '소프트 만년필 베이지 004',
    category: 'writing',
    price: 84600,
    discount_rate: 25,
    inventory: 58,
    image: '/images/products/write/004.jpg',
    description: '오피스데이의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2026-02-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '5',
    name: '미니멀 볼펜 그레이 005',
    category: 'writing',
    price: 1600,
    discount_rate: 15,
    inventory: 34,
    image: '/images/products/write/005.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-04-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '6',
    name: '클래식 만년필 라벤더 006',
    category: 'writing',
    price: 83700,
    discount_rate: 5,
    inventory: 5,
    image: '/images/products/write/006.jpg',
    description: '감성문구의 클래식 감성을 담은 만년필 상품입니다.',
    created_at: '2026-03-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '7',
    name: '오리지널 볼펜 브라운 007',
    category: 'writing',
    price: 7600,
    discount_rate: 25,
    inventory: 3,
    image: '/images/products/write/007.jpg',
    description: '페이퍼룸의 오리지널 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-12-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '8',
    name: '미니멀 만년필 브라운 008',
    category: 'writing',
    price: 40500,
    discount_rate: 25,
    inventory: 71,
    image: '/images/products/write/008.jpg',
    description: '오피스데이의 미니멀 감성을 담은 만년필 상품입니다.',
    created_at: '2025-05-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '9',
    name: '시그니처 볼펜 스카이블루 009',
    category: 'writing',
    price: 1300,
    discount_rate: 0,
    inventory: 109,
    image: '/images/products/write/009.jpg',
    description: '오피스데이의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-02-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '10',
    name: '데일리 만년필 라벤더 010',
    category: 'writing',
    price: 32800,
    discount_rate: 20,
    inventory: 101,
    image: '/images/products/write/010.jpg',
    description: '스튜디오노트의 데일리 감성을 담은 만년필 상품입니다.',
    created_at: '2025-06-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '11',
    name: '오리지널 볼펜 베이지 011',
    category: 'writing',
    price: 5100,
    discount_rate: 0,
    inventory: 63,
    image: '/images/products/write/011.jpg',
    description: '오피스데이의 오리지널 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-08-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '12',
    name: '프리미엄 만년필 블랙 012',
    category: 'writing',
    price: 36300,
    discount_rate: 0,
    inventory: 61,
    image: '/images/products/write/012.jpg',
    description: '감성문구의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2026-02-06',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '13',
    name: '베이직 볼펜 화이트 013',
    category: 'writing',
    price: 7700,
    discount_rate: 10,
    inventory: 100,
    image: '/images/products/write/013.jpg',
    description: '감성문구의 베이직 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-02',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '14',
    name: '시그니처 만년필 민트 014',
    category: 'writing',
    price: 32900,
    discount_rate: 5,
    inventory: 2,
    image: '/images/products/write/014.jpg',
    description: '아카이브문구의 시그니처 감성을 담은 만년필 상품입니다.',
    created_at: '2026-04-02',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '15',
    name: '프리미엄 볼펜 민트 015',
    category: 'writing',
    price: 3400,
    discount_rate: 0,
    inventory: 33,
    image: '/images/products/write/015.jpg',
    description: '페이퍼룸의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '16',
    name: '클래식 만년필 베이지 016',
    category: 'writing',
    price: 21100,
    discount_rate: 0,
    inventory: 21,
    image: '/images/products/write/016.jpg',
    description: '오피스데이의 클래식 감성을 담은 만년필 상품입니다.',
    created_at: '2025-06-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '17',
    name: '소프트 볼펜 스카이블루 017',
    category: 'writing',
    price: 5400,
    discount_rate: 0,
    inventory: 71,
    image: '/images/products/write/017.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-02-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '18',
    name: '미니멀 만년필 네이비 018',
    category: 'writing',
    price: 67600,
    discount_rate: 0,
    inventory: 37,
    image: '/images/products/write/018.jpg',
    description: '아카이브문구의 미니멀 감성을 담은 만년필 상품입니다.',
    created_at: '2026-03-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '19',
    name: '시그니처 볼펜 민트 019',
    category: 'writing',
    price: 8200,
    discount_rate: 5,
    inventory: 57,
    image: '/images/products/write/019.jpg',
    description: '오피스데이의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-09-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '20',
    name: '시그니처 만년필 아이보리 020',
    category: 'writing',
    price: 64800,
    discount_rate: 0,
    inventory: 56,
    image: '/images/products/write/020.jpg',
    description: '페이퍼룸의 시그니처 감성을 담은 만년필 상품입니다.',
    created_at: '2026-04-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '21',
    name: '시그니처 볼펜 베이지 021',
    category: 'writing',
    price: 6600,
    discount_rate: 0,
    inventory: 62,
    image: '/images/products/write/021.jpg',
    description: '아카이브문구의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-12-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '22',
    name: '오리지널 만년필 그레이 022',
    category: 'writing',
    price: 61100,
    discount_rate: 5,
    inventory: 10,
    image: '/images/products/write/022.jpg',
    description: '데일리펜의 오리지널 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '23',
    name: '프리미엄 볼펜 아이보리 023',
    category: 'writing',
    price: 1800,
    discount_rate: 10,
    inventory: 46,
    image: '/images/products/write/023.jpg',
    description: '아카이브문구의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-08-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '24',
    name: '클래식 만년필 화이트 024',
    category: 'writing',
    price: 56400,
    discount_rate: 0,
    inventory: 45,
    image: '/images/products/write/024.jpg',
    description: '오피스데이의 클래식 감성을 담은 만년필 상품입니다.',
    created_at: '2026-01-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '25',
    name: '미니멀 볼펜 아이보리 025',
    category: 'writing',
    price: 8200,
    discount_rate: 10,
    inventory: 38,
    image: '/images/products/write/025.jpg',
    description: '오피스데이의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-07-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '26',
    name: '베이직 만년필 화이트 026',
    category: 'writing',
    price: 64200,
    discount_rate: 25,
    inventory: 68,
    image: '/images/products/write/026.jpg',
    description: '데일리펜의 베이직 감성을 담은 만년필 상품입니다.',
    created_at: '2025-10-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '27',
    name: '클래식 볼펜 아이보리 027',
    category: 'writing',
    price: 2900,
    discount_rate: 25,
    inventory: 76,
    image: '/images/products/write/027.jpg',
    description: '데일리펜의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-04-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '28',
    name: '데일리 만년필 라벤더 028',
    category: 'writing',
    price: 45700,
    discount_rate: 25,
    inventory: 85,
    image: '/images/products/write/028.jpg',
    description: '감성문구의 데일리 감성을 담은 만년필 상품입니다.',
    created_at: '2026-02-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '29',
    name: '클래식 볼펜 아이보리 029',
    category: 'writing',
    price: 6700,
    discount_rate: 15,
    inventory: 33,
    image: '/images/products/write/029.jpg',
    description: '오피스데이의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-05-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '30',
    name: '라이트 만년필 아이보리 030',
    category: 'writing',
    price: 65100,
    discount_rate: 10,
    inventory: 79,
    image: '/images/products/write/030.jpg',
    description: '데일리펜의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2026-02-11',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '31',
    name: '라이트 볼펜 스카이블루 031',
    category: 'writing',
    price: 5100,
    discount_rate: 0,
    inventory: 82,
    image: '/images/products/write/031.jpg',
    description: '감성문구의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-05-01',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '32',
    name: '데일리 만년필 베이지 032',
    category: 'writing',
    price: 83000,
    discount_rate: 5,
    inventory: 73,
    image: '/images/products/write/032.jpg',
    description: '데일리펜의 데일리 감성을 담은 만년필 상품입니다.',
    created_at: '2025-05-31',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '33',
    name: '미니멀 볼펜 라벤더 033',
    category: 'writing',
    price: 3400,
    discount_rate: 0,
    inventory: 32,
    image: '/images/products/write/033.jpg',
    description: '스튜디오노트의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '34',
    name: '오리지널 만년필 브라운 034',
    category: 'writing',
    price: 46500,
    discount_rate: 0,
    inventory: 112,
    image: '/images/products/write/034.jpg',
    description: '오피스데이의 오리지널 감성을 담은 만년필 상품입니다.',
    created_at: '2025-07-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '35',
    name: '베이직 볼펜 네이비 035',
    category: 'writing',
    price: 1300,
    discount_rate: 5,
    inventory: 53,
    image: '/images/products/write/035.jpg',
    description: '페이퍼룸의 베이직 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-09-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '36',
    name: '소프트 만년필 블랙 036',
    category: 'writing',
    price: 62300,
    discount_rate: 0,
    inventory: 114,
    image: '/images/products/write/036.jpg',
    description: '아카이브문구의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2026-03-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '37',
    name: '프리미엄 볼펜 브라운 037',
    category: 'writing',
    price: 3500,
    discount_rate: 25,
    inventory: 46,
    image: '/images/products/write/037.jpg',
    description: '감성문구의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-06-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '38',
    name: '미니멀 만년필 베이지 038',
    category: 'writing',
    price: 66500,
    discount_rate: 25,
    inventory: 55,
    image: '/images/products/write/038.jpg',
    description: '스튜디오노트의 미니멀 감성을 담은 만년필 상품입니다.',
    created_at: '2025-12-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '39',
    name: '베이직 볼펜 베이지 039',
    category: 'writing',
    price: 1400,
    discount_rate: 0,
    inventory: 30,
    image: '/images/products/write/039.jpg',
    description: '아카이브문구의 베이직 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-11-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '40',
    name: '소프트 만년필 브라운 040',
    category: 'writing',
    price: 36000,
    discount_rate: 10,
    inventory: 100,
    image: '/images/products/write/040.jpg',
    description: '감성문구의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '41',
    name: '라이트 볼펜 네이비 041',
    category: 'writing',
    price: 4700,
    discount_rate: 0,
    inventory: 17,
    image: '/images/products/write/041.jpg',
    description: '페이퍼룸의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-06-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '42',
    name: '데일리 만년필 블랙 042',
    category: 'writing',
    price: 74000,
    discount_rate: 0,
    inventory: 84,
    image: '/images/products/write/042.jpg',
    description: '펜앤페이퍼의 데일리 감성을 담은 만년필 상품입니다.',
    created_at: '2025-07-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '43',
    name: '프리미엄 볼펜 민트 043',
    category: 'writing',
    price: 5500,
    discount_rate: 0,
    inventory: 96,
    image: '/images/products/write/043.jpg',
    description: '데일리펜의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-02-11',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '44',
    name: '프리미엄 만년필 민트 044',
    category: 'writing',
    price: 78900,
    discount_rate: 15,
    inventory: 111,
    image: '/images/products/write/044.jpg',
    description: '오피스데이의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2025-10-02',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '45',
    name: '라이트 볼펜 블랙 045',
    category: 'writing',
    price: 8100,
    discount_rate: 5,
    inventory: 30,
    image: '/images/products/write/045.jpg',
    description: '오피스데이의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-12-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '46',
    name: '시그니처 만년필 민트 046',
    category: 'writing',
    price: 76600,
    discount_rate: 0,
    inventory: 44,
    image: '/images/products/write/046.jpg',
    description: '데일리펜의 시그니처 감성을 담은 만년필 상품입니다.',
    created_at: '2025-06-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '47',
    name: '베이직 볼펜 화이트 047',
    category: 'writing',
    price: 8400,
    discount_rate: 10,
    inventory: 48,
    image: '/images/products/write/047.jpg',
    description: '스튜디오노트의 베이직 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-05-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '48',
    name: '클래식 만년필 그레이 048',
    category: 'writing',
    price: 52300,
    discount_rate: 0,
    inventory: 4,
    image: '/images/products/write/048.jpg',
    description: '페이퍼룸의 클래식 감성을 담은 만년필 상품입니다.',
    created_at: '2026-04-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '49',
    name: '미니멀 볼펜 화이트 049',
    category: 'writing',
    price: 6900,
    discount_rate: 20,
    inventory: 70,
    image: '/images/products/write/049.jpg',
    description: '스튜디오노트의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-01-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '50',
    name: '데일리 만년필 네이비 050',
    category: 'writing',
    price: 42300,
    discount_rate: 15,
    inventory: 89,
    image: '/images/products/write/050.jpg',
    description: '모노라인의 데일리 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '51',
    name: '프리미엄 볼펜 블랙 051',
    category: 'writing',
    price: 5400,
    discount_rate: 0,
    inventory: 9,
    image: '/images/products/write/051.jpg',
    description: '감성문구의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '52',
    name: '빈티지 만년필 스카이블루 052',
    category: 'writing',
    price: 70500,
    discount_rate: 25,
    inventory: 95,
    image: '/images/products/write/052.jpg',
    description: '페이퍼룸의 빈티지 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-27',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '53',
    name: '라이트 볼펜 라벤더 053',
    category: 'writing',
    price: 2600,
    discount_rate: 0,
    inventory: 32,
    image: '/images/products/write/053.jpg',
    description: '모노라인의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-02-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '54',
    name: '프리미엄 만년필 화이트 054',
    category: 'writing',
    price: 64400,
    discount_rate: 0,
    inventory: 44,
    image: '/images/products/write/054.jpg',
    description: '페이퍼룸의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '55',
    name: '클래식 볼펜 라벤더 055',
    category: 'writing',
    price: 2700,
    discount_rate: 0,
    inventory: 55,
    image: '/images/products/write/055.jpg',
    description: '데일리펜의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-05-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '56',
    name: '라이트 만년필 베이지 056',
    category: 'writing',
    price: 54800,
    discount_rate: 10,
    inventory: 6,
    image: '/images/products/write/056.jpg',
    description: '펜앤페이퍼의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-10-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '57',
    name: '미니멀 볼펜 블랙 057',
    category: 'writing',
    price: 4600,
    discount_rate: 20,
    inventory: 60,
    image: '/images/products/write/057.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-08-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '58',
    name: '빈티지 만년필 라벤더 058',
    category: 'writing',
    price: 48100,
    discount_rate: 20,
    inventory: 29,
    image: '/images/products/write/058.jpg',
    description: '스튜디오노트의 빈티지 감성을 담은 만년필 상품입니다.',
    created_at: '2026-04-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '59',
    name: '프리미엄 볼펜 그레이 059',
    category: 'writing',
    price: 3900,
    discount_rate: 0,
    inventory: 21,
    image: '/images/products/write/059.jpg',
    description: '데일리펜의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-27',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '60',
    name: '프리미엄 만년필 스카이블루 060',
    category: 'writing',
    price: 43100,
    discount_rate: 20,
    inventory: 106,
    image: '/images/products/write/060.jpg',
    description: '오피스데이의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2025-12-23',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '61',
    name: '클래식 볼펜 네이비 061',
    category: 'writing',
    price: 3400,
    discount_rate: 0,
    inventory: 116,
    image: '/images/products/write/061.jpg',
    description: '감성문구의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '62',
    name: '베이직 만년필 민트 062',
    category: 'writing',
    price: 37200,
    discount_rate: 5,
    inventory: 102,
    image: '/images/products/write/062.jpg',
    description: '감성문구의 베이직 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '63',
    name: '미니멀 볼펜 스카이블루 063',
    category: 'writing',
    price: 7900,
    discount_rate: 0,
    inventory: 0,
    image: '/images/products/write/063.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-07-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '64',
    name: '소프트 만년필 베이지 064',
    category: 'writing',
    price: 84500,
    discount_rate: 0,
    inventory: 18,
    image: '/images/products/write/064.jpg',
    description: '페이퍼룸의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '65',
    name: '프리미엄 볼펜 화이트 065',
    category: 'writing',
    price: 4200,
    discount_rate: 15,
    inventory: 87,
    image: '/images/products/write/065.jpg',
    description: '데일리펜의 프리미엄 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '66',
    name: '소프트 만년필 화이트 066',
    category: 'writing',
    price: 78900,
    discount_rate: 0,
    inventory: 24,
    image: '/images/products/write/066.jpg',
    description: '아카이브문구의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-12-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '67',
    name: '시그니처 볼펜 브라운 067',
    category: 'writing',
    price: 2400,
    discount_rate: 20,
    inventory: 17,
    image: '/images/products/write/067.jpg',
    description: '오피스데이의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-11-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '68',
    name: '오리지널 만년필 라벤더 068',
    category: 'writing',
    price: 63000,
    discount_rate: 0,
    inventory: 92,
    image: '/images/products/write/068.jpg',
    description: '데일리펜의 오리지널 감성을 담은 만년필 상품입니다.',
    created_at: '2026-03-06',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '69',
    name: '시그니처 볼펜 네이비 069',
    category: 'writing',
    price: 5900,
    discount_rate: 5,
    inventory: 117,
    image: '/images/products/write/069.jpg',
    description: '펜앤페이퍼의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-05-03',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '70',
    name: '베이직 만년필 화이트 070',
    category: 'writing',
    price: 29000,
    discount_rate: 0,
    inventory: 8,
    image: '/images/products/write/070.jpg',
    description: '펜앤페이퍼의 베이직 감성을 담은 만년필 상품입니다.',
    created_at: '2025-10-23',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '71',
    name: '시그니처 볼펜 그레이 071',
    category: 'writing',
    price: 6800,
    discount_rate: 15,
    inventory: 55,
    image: '/images/products/write/071.jpg',
    description: '모노라인의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-11-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '72',
    name: '클래식 만년필 블랙 072',
    category: 'writing',
    price: 17600,
    discount_rate: 20,
    inventory: 49,
    image: '/images/products/write/072.jpg',
    description: '오피스데이의 클래식 감성을 담은 만년필 상품입니다.',
    created_at: '2025-05-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '73',
    name: '소프트 볼펜 브라운 073',
    category: 'writing',
    price: 8400,
    discount_rate: 25,
    inventory: 82,
    image: '/images/products/write/073.jpg',
    description: '데일리펜의 소프트 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-31',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '74',
    name: '소프트 만년필 아이보리 074',
    category: 'writing',
    price: 44200,
    discount_rate: 5,
    inventory: 69,
    image: '/images/products/write/074.jpg',
    description: '감성문구의 소프트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-23',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '75',
    name: '베이직 볼펜 화이트 075',
    category: 'writing',
    price: 2600,
    discount_rate: 0,
    inventory: 82,
    image: '/images/products/write/075.jpg',
    description: '모노라인의 베이직 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-11-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '76',
    name: '라이트 만년필 민트 076',
    category: 'writing',
    price: 20300,
    discount_rate: 0,
    inventory: 53,
    image: '/images/products/write/076.jpg',
    description: '스튜디오노트의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-09-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '77',
    name: '클래식 볼펜 화이트 077',
    category: 'writing',
    price: 1700,
    discount_rate: 0,
    inventory: 35,
    image: '/images/products/write/077.jpg',
    description: '스튜디오노트의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-08-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '78',
    name: '미니멀 만년필 화이트 078',
    category: 'writing',
    price: 35300,
    discount_rate: 10,
    inventory: 96,
    image: '/images/products/write/078.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 만년필 상품입니다.',
    created_at: '2025-10-31',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '79',
    name: '라이트 볼펜 화이트 079',
    category: 'writing',
    price: 3300,
    discount_rate: 0,
    inventory: 61,
    image: '/images/products/write/079.jpg',
    description: '스튜디오노트의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-08-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '80',
    name: '프리미엄 만년필 네이비 080',
    category: 'writing',
    price: 60000,
    discount_rate: 0,
    inventory: 115,
    image: '/images/products/write/080.jpg',
    description: '아카이브문구의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2026-01-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '81',
    name: '빈티지 볼펜 네이비 081',
    category: 'writing',
    price: 2200,
    discount_rate: 15,
    inventory: 7,
    image: '/images/products/write/081.jpg',
    description: '데일리펜의 빈티지 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-12-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '82',
    name: '라이트 만년필 블랙 082',
    category: 'writing',
    price: 32200,
    discount_rate: 20,
    inventory: 11,
    image: '/images/products/write/082.jpg',
    description: '펜앤페이퍼의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2026-03-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '83',
    name: '데일리 볼펜 민트 083',
    category: 'writing',
    price: 5800,
    discount_rate: 0,
    inventory: 54,
    image: '/images/products/write/083.jpg',
    description: '오피스데이의 데일리 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-12-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '84',
    name: '빈티지 만년필 화이트 084',
    category: 'writing',
    price: 53900,
    discount_rate: 15,
    inventory: 81,
    image: '/images/products/write/084.jpg',
    description: '모노라인의 빈티지 감성을 담은 만년필 상품입니다.',
    created_at: '2025-07-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '85',
    name: '빈티지 볼펜 민트 085',
    category: 'writing',
    price: 8400,
    discount_rate: 20,
    inventory: 60,
    image: '/images/products/write/085.jpg',
    description: '오피스데이의 빈티지 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-07-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '86',
    name: '시그니처 만년필 베이지 086',
    category: 'writing',
    price: 35800,
    discount_rate: 0,
    inventory: 87,
    image: '/images/products/write/086.jpg',
    description: '모노라인의 시그니처 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '87',
    name: '클래식 볼펜 아이보리 087',
    category: 'writing',
    price: 7400,
    discount_rate: 0,
    inventory: 98,
    image: '/images/products/write/087.jpg',
    description: '아카이브문구의 클래식 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-01-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '88',
    name: '오리지널 만년필 네이비 088',
    category: 'writing',
    price: 51900,
    discount_rate: 0,
    inventory: 43,
    image: '/images/products/write/088.jpg',
    description: '모노라인의 오리지널 감성을 담은 만년필 상품입니다.',
    created_at: '2025-12-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '89',
    name: '라이트 볼펜 블랙 089',
    category: 'writing',
    price: 5000,
    discount_rate: 25,
    inventory: 97,
    image: '/images/products/write/089.jpg',
    description: '모노라인의 라이트 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '90',
    name: '라이트 만년필 블랙 090',
    category: 'writing',
    price: 70300,
    discount_rate: 5,
    inventory: 34,
    image: '/images/products/write/090.jpg',
    description: '페이퍼룸의 라이트 감성을 담은 만년필 상품입니다.',
    created_at: '2025-07-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '91',
    name: '오리지널 볼펜 베이지 091',
    category: 'writing',
    price: 5500,
    discount_rate: 25,
    inventory: 78,
    image: '/images/products/write/091.jpg',
    description: '아카이브문구의 오리지널 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-31',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '92',
    name: '프리미엄 만년필 그레이 092',
    category: 'writing',
    price: 73300,
    discount_rate: 25,
    inventory: 48,
    image: '/images/products/write/092.jpg',
    description: '스튜디오노트의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2025-08-18',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '93',
    name: '시그니처 볼펜 화이트 093',
    category: 'writing',
    price: 2500,
    discount_rate: 0,
    inventory: 88,
    image: '/images/products/write/093.jpg',
    description: '스튜디오노트의 시그니처 감성을 담은 볼펜 상품입니다.',
    created_at: '2025-10-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '94',
    name: '프리미엄 만년필 민트 094',
    category: 'writing',
    price: 76100,
    discount_rate: 10,
    inventory: 26,
    image: '/images/products/write/094.jpg',
    description: '감성문구의 프리미엄 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '95',
    name: '소프트 볼펜 블랙 095',
    category: 'writing',
    price: 4900,
    discount_rate: 5,
    inventory: 40,
    image: '/images/products/write/095.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-04-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '96',
    name: '빈티지 만년필 화이트 096',
    category: 'writing',
    price: 26800,
    discount_rate: 25,
    inventory: 0,
    image: '/images/products/write/096.jpg',
    description: '모노라인의 빈티지 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '97',
    name: '데일리 볼펜 블랙 097',
    category: 'writing',
    price: 1600,
    discount_rate: 25,
    inventory: 47,
    image: '/images/products/write/097.jpg',
    description: '모노라인의 데일리 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-03-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '98',
    name: '베이직 만년필 그레이 098',
    category: 'writing',
    price: 48000,
    discount_rate: 5,
    inventory: 40,
    image: '/images/products/write/098.jpg',
    description: '오피스데이의 베이직 감성을 담은 만년필 상품입니다.',
    created_at: '2025-11-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: '99',
    name: '데일리 볼펜 스카이블루 099',
    category: 'writing',
    price: 5700,
    discount_rate: 0,
    inventory: 87,
    image: '/images/products/write/099.jpg',
    description: '데일리펜의 데일리 감성을 담은 볼펜 상품입니다.',
    created_at: '2026-02-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '베이직 만년필 네이비 100',
    category: 'writing',
    price: 34100,
    discount_rate: 0,
    inventory: 100,
    image: '/images/products/write/100.jpg',
    description: '감성문구의 베이직 감성을 담은 만년필 상품입니다.',
    created_at: '2025-06-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '시그니처 메모지 라벤더 101',
    category: 'paper',
    price: 3700,
    discount_rate: 0,
    inventory: 109,
    image: '/images/products/paper/101.jpg',
    description: '감성문구의 시그니처 감성을 담은 메모지 상품입니다.',
    created_at: '2026-04-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '오리지널 편지 베이지 102',
    category: 'paper',
    price: 6000,
    discount_rate: 5,
    inventory: 82,
    image: '/images/products/paper/102.jpg',
    description: '모노라인의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2026-01-11',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '소프트 공책 브라운 103',
    category: 'paper',
    price: 7900,
    discount_rate: 0,
    inventory: 58,
    image: '/images/products/paper/103.jpg',
    description: '데일리펜의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2025-11-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '클래식 메모지 브라운 104',
    category: 'paper',
    price: 5400,
    discount_rate: 5,
    inventory: 117,
    image: '/images/products/paper/104.jpg',
    description: '페이퍼룸의 클래식 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '베이직 편지 브라운 105',
    category: 'paper',
    price: 8800,
    discount_rate: 15,
    inventory: 115,
    image: '/images/products/paper/105.jpg',
    description: '펜앤페이퍼의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2025-09-27',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '프리미엄 공책 블랙 106',
    category: 'paper',
    price: 16000,
    discount_rate: 5,
    inventory: 83,
    image: '/images/products/paper/106.jpg',
    description: '감성문구의 프리미엄 감성을 담은 공책 상품입니다.',
    created_at: '2025-09-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '라이트 메모지 그레이 107',
    category: 'paper',
    price: 4900,
    discount_rate: 0,
    inventory: 13,
    image: '/images/products/paper/107.jpg',
    description: '아카이브문구의 라이트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '시그니처 편지 화이트 108',
    category: 'paper',
    price: 7900,
    discount_rate: 15,
    inventory: 18,
    image: '/images/products/paper/108.jpg',
    description: '스튜디오노트의 시그니처 감성을 담은 편지 상품입니다.',
    created_at: '2026-04-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '빈티지 공책 화이트 109',
    category: 'paper',
    price: 9800,
    discount_rate: 0,
    inventory: 69,
    image: '/images/products/paper/109.jpg',
    description: '펜앤페이퍼의 빈티지 감성을 담은 공책 상품입니다.',
    created_at: '2026-03-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '데일리 메모지 브라운 110',
    category: 'paper',
    price: 5100,
    discount_rate: 0,
    inventory: 69,
    image: '/images/products/paper/110.jpg',
    description: '아카이브문구의 데일리 감성을 담은 메모지 상품입니다.',
    created_at: '2025-07-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '클래식 편지 화이트 111',
    category: 'paper',
    price: 7500,
    discount_rate: 0,
    inventory: 49,
    image: '/images/products/paper/111.jpg',
    description: '스튜디오노트의 클래식 감성을 담은 편지 상품입니다.',
    created_at: '2025-12-26',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '빈티지 공책 그레이 112',
    category: 'paper',
    price: 7800,
    discount_rate: 0,
    inventory: 49,
    image: '/images/products/paper/112.jpg',
    description: '펜앤페이퍼의 빈티지 감성을 담은 공책 상품입니다.',
    created_at: '2026-01-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '소프트 메모지 스카이블루 113',
    category: 'paper',
    price: 5600,
    discount_rate: 15,
    inventory: 50,
    image: '/images/products/paper/113.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-10-11',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '미니멀 편지 아이보리 114',
    category: 'paper',
    price: 3300,
    discount_rate: 0,
    inventory: 62,
    image: '/images/products/paper/114.jpg',
    description: '모노라인의 미니멀 감성을 담은 편지 상품입니다.',
    created_at: '2025-07-01',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '미니멀 공책 브라운 115',
    category: 'paper',
    price: 10000,
    discount_rate: 10,
    inventory: 59,
    image: '/images/products/paper/115.jpg',
    description: '스튜디오노트의 미니멀 감성을 담은 공책 상품입니다.',
    created_at: '2025-11-27',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '빈티지 메모지 블랙 116',
    category: 'paper',
    price: 2800,
    discount_rate: 0,
    inventory: 46,
    image: '/images/products/paper/116.jpg',
    description: '데일리펜의 빈티지 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-15',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '소프트 편지 베이지 117',
    category: 'paper',
    price: 7000,
    discount_rate: 15,
    inventory: 4,
    image: '/images/products/paper/117.jpg',
    description: '데일리펜의 소프트 감성을 담은 편지 상품입니다.',
    created_at: '2026-04-06',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '베이직 공책 베이지 118',
    category: 'paper',
    price: 7900,
    discount_rate: 10,
    inventory: 47,
    image: '/images/products/paper/118.jpg',
    description: '감성문구의 베이직 감성을 담은 공책 상품입니다.',
    created_at: '2025-06-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '프리미엄 메모지 베이지 119',
    category: 'paper',
    price: 2500,
    discount_rate: 0,
    inventory: 13,
    image: '/images/products/paper/119.jpg',
    description: '모노라인의 프리미엄 감성을 담은 메모지 상품입니다.',
    created_at: '2025-10-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '오리지널 편지 민트 120',
    category: 'paper',
    price: 3000,
    discount_rate: 5,
    inventory: 74,
    image: '/images/products/paper/120.jpg',
    description: '모노라인의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2025-07-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '소프트 공책 브라운 121',
    category: 'paper',
    price: 8000,
    discount_rate: 10,
    inventory: 65,
    image: '/images/products/paper/121.jpg',
    description: '데일리펜의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '오리지널 메모지 베이지 122',
    category: 'paper',
    price: 5200,
    discount_rate: 20,
    inventory: 11,
    image: '/images/products/paper/122.jpg',
    description: '펜앤페이퍼의 오리지널 감성을 담은 메모지 상품입니다.',
    created_at: '2025-06-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '베이직 편지 민트 123',
    category: 'paper',
    price: 4200,
    discount_rate: 0,
    inventory: 28,
    image: '/images/products/paper/123.jpg',
    description: '감성문구의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2025-08-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '라이트 공책 그레이 124',
    category: 'paper',
    price: 9700,
    discount_rate: 0,
    inventory: 7,
    image: '/images/products/paper/124.jpg',
    description: '감성문구의 라이트 감성을 담은 공책 상품입니다.',
    created_at: '2025-09-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '데일리 메모지 민트 125',
    category: 'paper',
    price: 2700,
    discount_rate: 20,
    inventory: 58,
    image: '/images/products/paper/125.jpg',
    description: '감성문구의 데일리 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '미니멀 편지 베이지 126',
    category: 'paper',
    price: 3800,
    discount_rate: 15,
    inventory: 26,
    image: '/images/products/paper/126.jpg',
    description: '아카이브문구의 미니멀 감성을 담은 편지 상품입니다.',
    created_at: '2025-10-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '미니멀 공책 베이지 127',
    category: 'paper',
    price: 7800,
    discount_rate: 15,
    inventory: 71,
    image: '/images/products/paper/127.jpg',
    description: '아카이브문구의 미니멀 감성을 담은 공책 상품입니다.',
    created_at: '2025-09-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '프리미엄 메모지 브라운 128',
    category: 'paper',
    price: 4000,
    discount_rate: 0,
    inventory: 19,
    image: '/images/products/paper/128.jpg',
    description: '펜앤페이퍼의 프리미엄 감성을 담은 메모지 상품입니다.',
    created_at: '2026-01-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '소프트 편지 라벤더 129',
    category: 'paper',
    price: 7900,
    discount_rate: 0,
    inventory: 39,
    image: '/images/products/paper/129.jpg',
    description: '아카이브문구의 소프트 감성을 담은 편지 상품입니다.',
    created_at: '2025-05-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '오리지널 공책 민트 130',
    category: 'paper',
    price: 15700,
    discount_rate: 25,
    inventory: 5,
    image: '/images/products/paper/130.jpg',
    description: '스튜디오노트의 오리지널 감성을 담은 공책 상품입니다.',
    created_at: '2025-06-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '오리지널 메모지 블랙 131',
    category: 'paper',
    price: 5400,
    discount_rate: 0,
    inventory: 29,
    image: '/images/products/paper/131.jpg',
    description: '아카이브문구의 오리지널 감성을 담은 메모지 상품입니다.',
    created_at: '2026-02-15',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '오리지널 편지 베이지 132',
    category: 'paper',
    price: 4200,
    discount_rate: 25,
    inventory: 67,
    image: '/images/products/paper/132.jpg',
    description: '페이퍼룸의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2026-02-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '소프트 공책 네이비 133',
    category: 'paper',
    price: 14600,
    discount_rate: 25,
    inventory: 120,
    image: '/images/products/paper/133.jpg',
    description: '데일리펜의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2026-03-02',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '베이직 메모지 그레이 134',
    category: 'paper',
    price: 2800,
    discount_rate: 0,
    inventory: 8,
    image: '/images/products/paper/134.jpg',
    description: '모노라인의 베이직 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '데일리 편지 베이지 135',
    category: 'paper',
    price: 6500,
    discount_rate: 20,
    inventory: 85,
    image: '/images/products/paper/135.jpg',
    description: '데일리펜의 데일리 감성을 담은 편지 상품입니다.',
    created_at: '2026-01-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '라이트 공책 스카이블루 136',
    category: 'paper',
    price: 6600,
    discount_rate: 10,
    inventory: 73,
    image: '/images/products/paper/136.jpg',
    description: '감성문구의 라이트 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '데일리 메모지 베이지 137',
    category: 'paper',
    price: 6400,
    discount_rate: 15,
    inventory: 103,
    image: '/images/products/paper/137.jpg',
    description: '펜앤페이퍼의 데일리 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '미니멀 편지 라벤더 138',
    category: 'paper',
    price: 7900,
    discount_rate: 25,
    inventory: 107,
    image: '/images/products/paper/138.jpg',
    description: '오피스데이의 미니멀 감성을 담은 편지 상품입니다.',
    created_at: '2025-10-15',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '시그니처 공책 라벤더 139',
    category: 'paper',
    price: 13300,
    discount_rate: 10,
    inventory: 52,
    image: '/images/products/paper/139.jpg',
    description: '페이퍼룸의 시그니처 감성을 담은 공책 상품입니다.',
    created_at: '2025-11-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '오리지널 메모지 화이트 140',
    category: 'paper',
    price: 4000,
    discount_rate: 5,
    inventory: 51,
    image: '/images/products/paper/140.jpg',
    description: '아카이브문구의 오리지널 감성을 담은 메모지 상품입니다.',
    created_at: '2025-12-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '소프트 편지 라벤더 141',
    category: 'paper',
    price: 8600,
    discount_rate: 0,
    inventory: 113,
    image: '/images/products/paper/141.jpg',
    description: '오피스데이의 소프트 감성을 담은 편지 상품입니다.',
    created_at: '2025-05-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '프리미엄 공책 민트 142',
    category: 'paper',
    price: 7100,
    discount_rate: 25,
    inventory: 73,
    image: '/images/products/paper/142.jpg',
    description: '감성문구의 프리미엄 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-04',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '오리지널 메모지 스카이블루 143',
    category: 'paper',
    price: 4900,
    discount_rate: 5,
    inventory: 39,
    image: '/images/products/paper/143.jpg',
    description: '아카이브문구의 오리지널 감성을 담은 메모지 상품입니다.',
    created_at: '2025-09-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '프리미엄 편지 그레이 144',
    category: 'paper',
    price: 8400,
    discount_rate: 0,
    inventory: 114,
    image: '/images/products/paper/144.jpg',
    description: '데일리펜의 프리미엄 감성을 담은 편지 상품입니다.',
    created_at: '2025-12-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '시그니처 공책 베이지 145',
    category: 'paper',
    price: 3200,
    discount_rate: 15,
    inventory: 58,
    image: '/images/products/paper/145.jpg',
    description: '데일리펜의 시그니처 감성을 담은 공책 상품입니다.',
    created_at: '2025-08-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '데일리 메모지 화이트 146',
    category: 'paper',
    price: 2200,
    discount_rate: 0,
    inventory: 94,
    image: '/images/products/paper/146.jpg',
    description: '펜앤페이퍼의 데일리 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '미니멀 편지 아이보리 147',
    category: 'paper',
    price: 4400,
    discount_rate: 20,
    inventory: 73,
    image: '/images/products/paper/147.jpg',
    description: '데일리펜의 미니멀 감성을 담은 편지 상품입니다.',
    created_at: '2026-02-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '소프트 공책 브라운 148',
    category: 'paper',
    price: 4500,
    discount_rate: 25,
    inventory: 41,
    image: '/images/products/paper/148.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '빈티지 메모지 그레이 149',
    category: 'paper',
    price: 6400,
    discount_rate: 0,
    inventory: 62,
    image: '/images/products/paper/149.jpg',
    description: '페이퍼룸의 빈티지 감성을 담은 메모지 상품입니다.',
    created_at: '2026-02-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '시그니처 편지 네이비 150',
    category: 'paper',
    price: 7900,
    discount_rate: 25,
    inventory: 101,
    image: '/images/products/paper/150.jpg',
    description: '스튜디오노트의 시그니처 감성을 담은 편지 상품입니다.',
    created_at: '2025-09-27',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '소프트 공책 민트 151',
    category: 'paper',
    price: 10400,
    discount_rate: 15,
    inventory: 11,
    image: '/images/products/paper/151.jpg',
    description: '모노라인의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-18',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '소프트 메모지 스카이블루 152',
    category: 'paper',
    price: 2400,
    discount_rate: 0,
    inventory: 110,
    image: '/images/products/paper/152.jpg',
    description: '페이퍼룸의 소프트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-10-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '베이직 편지 베이지 153',
    category: 'paper',
    price: 5400,
    discount_rate: 0,
    inventory: 31,
    image: '/images/products/paper/153.jpg',
    description: '아카이브문구의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2026-03-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '미니멀 공책 브라운 154',
    category: 'paper',
    price: 9300,
    discount_rate: 0,
    inventory: 60,
    image: '/images/products/paper/154.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 공책 상품입니다.',
    created_at: '2025-06-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '소프트 메모지 스카이블루 155',
    category: 'paper',
    price: 2900,
    discount_rate: 0,
    inventory: 0,
    image: '/images/products/paper/155.jpg',
    description: '감성문구의 소프트 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '오리지널 편지 아이보리 156',
    category: 'paper',
    price: 6900,
    discount_rate: 10,
    inventory: 45,
    image: '/images/products/paper/156.jpg',
    description: '감성문구의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2026-02-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '데일리 공책 화이트 157',
    category: 'paper',
    price: 13300,
    discount_rate: 10,
    inventory: 10,
    image: '/images/products/paper/157.jpg',
    description: '스튜디오노트의 데일리 감성을 담은 공책 상품입니다.',
    created_at: '2025-08-07',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '데일리 메모지 민트 158',
    category: 'paper',
    price: 6300,
    discount_rate: 0,
    inventory: 8,
    image: '/images/products/paper/158.jpg',
    description: '모노라인의 데일리 감성을 담은 메모지 상품입니다.',
    created_at: '2025-12-22',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '시그니처 편지 그레이 159',
    category: 'paper',
    price: 6400,
    discount_rate: 5,
    inventory: 81,
    image: '/images/products/paper/159.jpg',
    description: '감성문구의 시그니처 감성을 담은 편지 상품입니다.',
    created_at: '2025-07-18',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '시그니처 공책 스카이블루 160',
    category: 'paper',
    price: 5800,
    discount_rate: 0,
    inventory: 41,
    image: '/images/products/paper/160.jpg',
    description: '감성문구의 시그니처 감성을 담은 공책 상품입니다.',
    created_at: '2025-09-06',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '베이직 메모지 라벤더 161',
    category: 'paper',
    price: 2900,
    discount_rate: 0,
    inventory: 42,
    image: '/images/products/paper/161.jpg',
    description: '페이퍼룸의 베이직 감성을 담은 메모지 상품입니다.',
    created_at: '2025-10-18',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '베이직 편지 베이지 162',
    category: 'paper',
    price: 3900,
    discount_rate: 15,
    inventory: 19,
    image: '/images/products/paper/162.jpg',
    description: '모노라인의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2026-01-15',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '시그니처 공책 화이트 163',
    category: 'paper',
    price: 14300,
    discount_rate: 0,
    inventory: 8,
    image: '/images/products/paper/163.jpg',
    description: '오피스데이의 시그니처 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '베이직 메모지 화이트 164',
    category: 'paper',
    price: 4100,
    discount_rate: 10,
    inventory: 75,
    image: '/images/products/paper/164.jpg',
    description: '스튜디오노트의 베이직 감성을 담은 메모지 상품입니다.',
    created_at: '2026-04-30',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '소프트 편지 라벤더 165',
    category: 'paper',
    price: 8900,
    discount_rate: 0,
    inventory: 2,
    image: '/images/products/paper/165.jpg',
    description: '아카이브문구의 소프트 감성을 담은 편지 상품입니다.',
    created_at: '2025-10-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '라이트 공책 라벤더 166',
    category: 'paper',
    price: 3000,
    discount_rate: 5,
    inventory: 107,
    image: '/images/products/paper/166.jpg',
    description: '감성문구의 라이트 감성을 담은 공책 상품입니다.',
    created_at: '2025-05-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '라이트 메모지 민트 167',
    category: 'paper',
    price: 2000,
    discount_rate: 15,
    inventory: 95,
    image: '/images/products/paper/167.jpg',
    description: '펜앤페이퍼의 라이트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-28',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '빈티지 편지 민트 168',
    category: 'paper',
    price: 2600,
    discount_rate: 0,
    inventory: 60,
    image: '/images/products/paper/168.jpg',
    description: '페이퍼룸의 빈티지 감성을 담은 편지 상품입니다.',
    created_at: '2025-11-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '빈티지 공책 스카이블루 169',
    category: 'paper',
    price: 7500,
    discount_rate: 0,
    inventory: 73,
    image: '/images/products/paper/169.jpg',
    description: '데일리펜의 빈티지 감성을 담은 공책 상품입니다.',
    created_at: '2026-02-16',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '라이트 메모지 아이보리 170',
    category: 'paper',
    price: 5700,
    discount_rate: 15,
    inventory: 34,
    image: '/images/products/paper/170.jpg',
    description: '펜앤페이퍼의 라이트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-09-09',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '오리지널 편지 스카이블루 171',
    category: 'paper',
    price: 4600,
    discount_rate: 25,
    inventory: 114,
    image: '/images/products/paper/171.jpg',
    description: '페이퍼룸의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2025-07-18',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '오리지널 공책 그레이 172',
    category: 'paper',
    price: 4800,
    discount_rate: 20,
    inventory: 14,
    image: '/images/products/paper/172.jpg',
    description: '펜앤페이퍼의 오리지널 감성을 담은 공책 상품입니다.',
    created_at: '2025-09-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '시그니처 메모지 화이트 173',
    category: 'paper',
    price: 4800,
    discount_rate: 25,
    inventory: 58,
    image: '/images/products/paper/173.jpg',
    description: '스튜디오노트의 시그니처 감성을 담은 메모지 상품입니다.',
    created_at: '2025-07-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '라이트 편지 민트 174',
    category: 'paper',
    price: 6100,
    discount_rate: 5,
    inventory: 63,
    image: '/images/products/paper/174.jpg',
    description: '모노라인의 라이트 감성을 담은 편지 상품입니다.',
    created_at: '2025-06-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '클래식 공책 화이트 175',
    category: 'paper',
    price: 14200,
    discount_rate: 5,
    inventory: 42,
    image: '/images/products/paper/175.jpg',
    description: '아카이브문구의 클래식 감성을 담은 공책 상품입니다.',
    created_at: '2025-06-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '클래식 메모지 민트 176',
    category: 'paper',
    price: 4300,
    discount_rate: 15,
    inventory: 54,
    image: '/images/products/paper/176.jpg',
    description: '펜앤페이퍼의 클래식 감성을 담은 메모지 상품입니다.',
    created_at: '2026-03-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '베이직 편지 스카이블루 177',
    category: 'paper',
    price: 3000,
    discount_rate: 0,
    inventory: 75,
    image: '/images/products/paper/177.jpg',
    description: '페이퍼룸의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2025-07-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '데일리 공책 브라운 178',
    category: 'paper',
    price: 3200,
    discount_rate: 10,
    inventory: 56,
    image: '/images/products/paper/178.jpg',
    description: '감성문구의 데일리 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '시그니처 메모지 민트 179',
    category: 'paper',
    price: 3000,
    discount_rate: 5,
    inventory: 53,
    image: '/images/products/paper/179.jpg',
    description: '스튜디오노트의 시그니처 감성을 담은 메모지 상품입니다.',
    created_at: '2025-12-31',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '빈티지 편지 아이보리 180',
    category: 'paper',
    price: 5200,
    discount_rate: 0,
    inventory: 111,
    image: '/images/products/paper/180.jpg',
    description: '오피스데이의 빈티지 감성을 담은 편지 상품입니다.',
    created_at: '2025-12-13',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '클래식 공책 라벤더 181',
    category: 'paper',
    price: 15500,
    discount_rate: 15,
    inventory: 120,
    image: '/images/products/paper/181.jpg',
    description: '펜앤페이퍼의 클래식 감성을 담은 공책 상품입니다.',
    created_at: '2026-04-19',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '클래식 메모지 블랙 182',
    category: 'paper',
    price: 2200,
    discount_rate: 0,
    inventory: 83,
    image: '/images/products/paper/182.jpg',
    description: '데일리펜의 클래식 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '베이직 편지 화이트 183',
    category: 'paper',
    price: 8700,
    discount_rate: 10,
    inventory: 51,
    image: '/images/products/paper/183.jpg',
    description: '데일리펜의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2026-02-15',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '미니멀 공책 아이보리 184',
    category: 'paper',
    price: 5000,
    discount_rate: 5,
    inventory: 62,
    image: '/images/products/paper/184.jpg',
    description: '감성문구의 미니멀 감성을 담은 공책 상품입니다.',
    created_at: '2026-01-29',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '오리지널 메모지 네이비 185',
    category: 'paper',
    price: 2100,
    discount_rate: 20,
    inventory: 106,
    image: '/images/products/paper/185.jpg',
    description: '오피스데이의 오리지널 감성을 담은 메모지 상품입니다.',
    created_at: '2026-01-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '미니멀 편지 라벤더 186',
    category: 'paper',
    price: 4600,
    discount_rate: 5,
    inventory: 100,
    image: '/images/products/paper/186.jpg',
    description: '페이퍼룸의 미니멀 감성을 담은 편지 상품입니다.',
    created_at: '2025-05-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '오리지널 공책 그레이 187',
    category: 'paper',
    price: 11300,
    discount_rate: 0,
    inventory: 100,
    image: '/images/products/paper/187.jpg',
    description: '데일리펜의 오리지널 감성을 담은 공책 상품입니다.',
    created_at: '2026-03-23',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '라이트 메모지 라벤더 188',
    category: 'paper',
    price: 1900,
    discount_rate: 25,
    inventory: 118,
    image: '/images/products/paper/188.jpg',
    description: '펜앤페이퍼의 라이트 감성을 담은 메모지 상품입니다.',
    created_at: '2026-02-24',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '프리미엄 편지 그레이 189',
    category: 'paper',
    price: 8200,
    discount_rate: 5,
    inventory: 82,
    image: '/images/products/paper/189.jpg',
    description: '오피스데이의 프리미엄 감성을 담은 편지 상품입니다.',
    created_at: '2026-03-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 10',
    name: '소프트 공책 민트 190',
    category: 'paper',
    price: 7200,
    discount_rate: 0,
    inventory: 67,
    image: '/images/products/paper/190.jpg',
    description: '펜앤페이퍼의 소프트 감성을 담은 공책 상품입니다.',
    created_at: '2025-11-17',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 11',
    name: '소프트 메모지 화이트 191',
    category: 'paper',
    price: 3600,
    discount_rate: 10,
    inventory: 79,
    image: '/images/products/paper/191.jpg',
    description: '오피스데이의 소프트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-11-21',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 12',
    name: '오리지널 편지 아이보리 192',
    category: 'paper',
    price: 7600,
    discount_rate: 20,
    inventory: 16,
    image: '/images/products/paper/192.jpg',
    description: '오피스데이의 오리지널 감성을 담은 편지 상품입니다.',
    created_at: '2026-01-25',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 13',
    name: '베이직 공책 아이보리 193',
    category: 'paper',
    price: 4400,
    discount_rate: 10,
    inventory: 75,
    image: '/images/products/paper/193.jpg',
    description: '페이퍼룸의 베이직 감성을 담은 공책 상품입니다.',
    created_at: '2025-07-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 14',
    name: '클래식 메모지 민트 194',
    category: 'paper',
    price: 4300,
    discount_rate: 10,
    inventory: 19,
    image: '/images/products/paper/194.jpg',
    description: '펜앤페이퍼의 클래식 감성을 담은 메모지 상품입니다.',
    created_at: '2026-04-14',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 15',
    name: '베이직 편지 라벤더 195',
    category: 'paper',
    price: 6900,
    discount_rate: 15,
    inventory: 58,
    image: '/images/products/paper/195.jpg',
    description: '데일리펜의 베이직 감성을 담은 편지 상품입니다.',
    created_at: '2026-01-23',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 16',
    name: '빈티지 공책 그레이 196',
    category: 'paper',
    price: 12500,
    discount_rate: 0,
    inventory: 40,
    image: '/images/products/paper/196.jpg',
    description: '스튜디오노트의 빈티지 감성을 담은 공책 상품입니다.',
    created_at: '2025-06-08',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 17',
    name: '소프트 메모지 네이비 197',
    category: 'paper',
    price: 3200,
    discount_rate: 5,
    inventory: 26,
    image: '/images/products/paper/197.jpg',
    description: '모노라인의 소프트 감성을 담은 메모지 상품입니다.',
    created_at: '2025-12-20',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 18',
    name: '클래식 편지 라벤더 198',
    category: 'paper',
    price: 6400,
    discount_rate: 25,
    inventory: 2,
    image: '/images/products/paper/198.jpg',
    description: '데일리펜의 클래식 감성을 담은 편지 상품입니다.',
    created_at: '2025-05-10',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 19',
    name: '시그니처 공책 화이트 199',
    category: 'paper',
    price: 9800,
    discount_rate: 15,
    inventory: 103,
    image: '/images/products/paper/199.jpg',
    description: '페이퍼룸의 시그니처 감성을 담은 공책 상품입니다.',
    created_at: '2026-02-05',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
  {
    id: ' 20',
    name: '미니멀 메모지 네이비 200',
    category: 'paper',
    price: 3000,
    discount_rate: 0,
    inventory: 17,
    image: '/images/products/paper/200.jpg',
    description: '아카이브문구의 미니멀 감성을 담은 메모지 상품입니다.',
    created_at: '2025-06-12',
    store_id:'store123',
    content:'데이터 넣기 힘드네요 화이팅~',
        state: 'ACTIVE',
  options:{
    color:['black','blue'],
    size:[200,400]
  },
    thumbnail_image:'/dummy_pen.jpg',
  },
] as const;
